### PR TITLE
Fixed getconf command in build instructions

### PR DESCRIPTION
**Pull request by pebble-24**
getconf NPROCESSORS_CONF isn't a valid command. The correct command is getconf _NPROCESSORS_CONF.

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]

**Comment by jbeich** [comment]
Please, revert. `nproc` fallback is an intentional compatibility with non-GNU systems. See [FreeBSD fix](https://github.com/freebsd/freebsd-src/commit/7b9730054781) and [POSIX fix](https://www.austingroupbugs.net/view.php?id=339). NetBSD and OpenBSD still don't support GNU-style with leading underscore.

**Comment by fufexan** [comment]
@jbeich is switching to the Ninja generator and dropping `nproc` entirely a suitable solution for BSD?

**Comment by jbeich** [comment]
Sure. All BSDs package ninja. On DragonFly ninja is unstable but it can probably replace it with `samu` (from samurai package) instead.

**Comment by jbeich** [comment]
Actually, DragonFly [avoids ninja](https://github.com/DragonFlyBSD/DeltaPorts/commit/13dc7a8b6a0) due to RPATH rather than stability.

**Comment by jbeich** [comment]
FWIW, getconf usage dates back to https://github.com/hyprwm/Hyprland/pull/2209/commits/e86d00e2243d and was copied here for consistency. Hyprland itself no longer uses nproc or getconf.

**Comment by fufexan** [comment]
Right, I've removed those in favor of the Ninja generator, as per [this comment](https://github.com/hyprwm/Hyprland/pull/5667#issuecomment-2094269016).

I can update the READMEs of the rest of the repos to use `-G Ninja` and add a note for DragonFly users to manually use `getconf NPROCESSORS_CONF`.

**Pull request merged**
