### PR TITLE
Relicense hyprlang to lgpl 3

### PR DESCRIPTION
**Pull request by vaxerski**
Due to some annoying license incompatibilities, GPL and BSD don't like each other, so I'd like to leave this to be more permissive.

cc all contributors, please leave a comment "I consent to this change" or I'll be forced to yeet your contributions.

@fufexan @solopasha @spikespaz @earboxer 

ref, gpl:
image

### CODE REVIEW

**Comment by fufexan** [comment]
I consent to this change.

Also, please change `nix/default.nix`'s `license` key from `licenses.gpl3Plus` to `licenses.bsd3`

**Comment by spikespaz** [comment]
All of my contributions released publicly to open source communities are henceforth transferred in ownership to the original Code Owner, who may do with them as he pleases, including but not exclusive to relicensing.

**Comment by solopasha** [comment]
Ok, i'm drunk rn, but I consent to this change

**Comment by earboxer** [comment]
> GPL and BSD don't like each other

BSD-3-Clause is compatible with GPLv3, it's just that GPLv3 is the viral license (giving users more permissions by preventing proprietary programs from linking to it).

If the issue is that you *want* non-free programs to be able to use this library (as suggested by the screenshot), then I suggest using LGPL-3.0-only. (In fact, I consent to license my past contributions to hyprlang under LGPL-3.0-only.)

See https://en.wikipedia.org/wiki/License_compatibility for more information.

**Comment by spikespaz** [comment]
@earboxer I was thinking the same thing but was too lazy to double check myself. I support this motive, the license should be LGPL.

**Comment by vaxerski** [comment]
ugh, fine.

**Comment by vaxerski** [comment]
I'll need all four of you to write again "I consent to having all my contributions to this repository relicensed to lgpl 3.0 only"

**Comment by solopasha** [comment]
I consent to having all my contributions to this repository relicensed to lgpl 3.0 only

**Comment by vaxerski** [comment]
@earboxer @spikespaz pretty please?

**Comment by spikespaz** [comment]
I consent to having all my contributions to this repository relicensed to LGPL-3.0-Only.

**Comment by earboxer** [comment]
I consent to having all my contributions to this repository relicensed to LGPL-3.0-Only.

**Comment by vaxerski** [comment]
top

**Pull request merged**
